export const data = [
  {
    customer_name: "Prestige Worldwide",
    date_created: "2023-07-01",
    compliance_status: "In Review",
    auditors: ["Ethan Wang", "Charlie Lee", "Alice Johnson","Ethan Wang", "Charlie Lee", "Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "CyberCore Tech",
    date_created: "2025-03-10",
    compliance_status: "Pending",
    auditors: ["Diana Patel", "Ethan Wang", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Stark Industries",
    date_created: "2023-07-14",
    compliance_status: "Pending",
    auditors: ["Alice Johnson", "Bob Smith", "Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Orbitronix",
    date_created: "2023-04-08",
    compliance_status: "Compliant",
    auditors: ["Diana Patel", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Black Mesa",
    date_created: "2023-07-04",
    compliance_status: "Compliant",
    auditors: ["Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "LexCorp",
    date_created: "2023-09-19",
    compliance_status: "Pending",
    auditors: ["Alice Johnson", "Diana Patel", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Monarch Solutions",
    date_created: "2025-06-09",
    compliance_status: "In Review",
    auditors: ["Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Zenith Corp",
    date_created: "2025-01-30",
    compliance_status: "In Review",
    auditors: ["Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Orbitronix",
    date_created: "2023-08-18",
    compliance_status: "In Review",
    auditors: ["Bob Smith", "Ethan Wang", "Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Vehement Capital",
    date_created: "2024-11-28",
    compliance_status: "Pending",
    auditors: ["Diana Patel", "Charlie Lee", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Paper Street Soap",
    date_created: "2025-03-20",
    compliance_status: "Pending",
    auditors: ["Charlie Lee", "Diana Patel", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Initech",
    date_created: "2024-02-10",
    compliance_status: "Pending",
    auditors: ["Alice Johnson", "Fiona Chen", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Hooli",
    date_created: "2024-08-08",
    compliance_status: "Non-Compliant",
    auditors: ["Diana Patel", "Bob Smith", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Black Mesa",
    date_created: "2025-06-06",
    compliance_status: "In Review",
    auditors: ["Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Paper Street Soap",
    date_created: "2024-02-15",
    compliance_status: "Pending",
    auditors: ["Ethan Wang", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Rich Industries",
    date_created: "2023-03-21",
    compliance_status: "Non-Compliant",
    auditors: ["Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Cyberdyne Systems",
    date_created: "2023-05-05",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Charlie Lee", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Sterling Cooper",
    date_created: "2023-10-18",
    compliance_status: "Non-Compliant",
    auditors: ["Diana Patel", "Ethan Wang", "Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Umbrella Corp",
    date_created: "2023-01-21",
    compliance_status: "Compliant",
    auditors: ["Fiona Chen", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "NextGen Systems",
    date_created: "2025-06-04",
    compliance_status: "Non-Compliant",
    auditors: ["Charlie Lee", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Rich Industries",
    date_created: "2024-04-11",
    compliance_status: "In Review",
    auditors: ["Alice Johnson", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Rich Industries",
    date_created: "2025-03-20",
    compliance_status: "Compliant",
    auditors: ["Charlie Lee", "Ethan Wang", "Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "TriOptimum",
    date_created: "2025-02-12",
    compliance_status: "Compliant",
    auditors: ["Ethan Wang", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Duff Brewery",
    date_created: "2024-05-22",
    compliance_status: "Pending",
    auditors: ["Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "NeonTech",
    date_created: "2024-03-14",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Rich Industries",
    date_created: "2023-06-01",
    compliance_status: "Non-Compliant",
    auditors: ["Fiona Chen", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Acme Corp",
    date_created: "2023-02-26",
    compliance_status: "In Review",
    auditors: ["Charlie Lee", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Pied Piper",
    date_created: "2024-09-21",
    compliance_status: "In Review",
    auditors: ["Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Monarch Solutions",
    date_created: "2024-04-02",
    compliance_status: "Non-Compliant",
    auditors: ["Diana Patel", "Fiona Chen", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Daily Planet",
    date_created: "2023-01-15",
    compliance_status: "In Review",
    auditors: ["Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Vought International",
    date_created: "2023-10-07",
    compliance_status: "Compliant",
    auditors: ["Diana Patel", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Shady Pines",
    date_created: "2023-10-27",
    compliance_status: "Non-Compliant",
    auditors: ["Bob Smith", "Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Nakatomi Trading",
    date_created: "2023-05-11",
    compliance_status: "Pending",
    auditors: ["Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Sterling Cooper",
    date_created: "2023-08-19",
    compliance_status: "Pending",
    auditors: ["Bob Smith", "Charlie Lee", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Pied Piper",
    date_created: "2024-05-21",
    compliance_status: "Compliant",
    auditors: ["Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Freeman Holdings",
    date_created: "2023-02-05",
    compliance_status: "Compliant",
    auditors: ["Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Vandelay Industries",
    date_created: "2024-06-05",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Umbrella Corp",
    date_created: "2023-10-21",
    compliance_status: "Compliant",
    auditors: ["Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Oscorp",
    date_created: "2023-12-26",
    compliance_status: "Pending",
    auditors: ["Charlie Lee", "Fiona Chen", "Diana Patel"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "E Corp",
    date_created: "2023-07-24",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Bob Smith", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Soylent Corp",
    date_created: "2024-06-15",
    compliance_status: "Pending",
    auditors: ["Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Soylent Corp",
    date_created: "2023-02-07",
    compliance_status: "Non-Compliant",
    auditors: ["Fiona Chen", "Diana Patel", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "NextGen Systems",
    date_created: "2024-08-30",
    compliance_status: "In Review",
    auditors: ["Alice Johnson", "Fiona Chen", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Redwood Digital",
    date_created: "2024-09-14",
    compliance_status: "Non-Compliant",
    auditors: ["Ethan Wang", "Bob Smith", "Fiona Chen"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Oscorp",
    date_created: "2024-10-02",
    compliance_status: "Non-Compliant",
    auditors: ["Bob Smith", "Alice Johnson", "Ethan Wang"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Stark Industries",
    date_created: "2023-10-24",
    compliance_status: "Non-Compliant",
    auditors: ["Charlie Lee", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "LexCorp",
    date_created: "2023-03-19",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Alice Johnson", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Sterling Cooper",
    date_created: "2025-02-24",
    compliance_status: "Compliant",
    auditors: ["Fiona Chen", "Alice Johnson"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Oceanic Airlines",
    date_created: "2023-02-09",
    compliance_status: "Pending",
    auditors: ["Diana Patel", "Alice Johnson", "Charlie Lee"],
    actions: ["view", "edit", "delete"],
  },
  {
    customer_name: "Oceanic Airlines",
    date_created: "2023-08-06",
    compliance_status: "In Review",
    auditors: ["Diana Patel", "Bob Smith"],
    actions: ["view", "edit", "delete"],
  },
];
